- src/__tests__/index.spec.ts
- src/resolver/resolver.ts
This makes the behaviour consistent no matter the order of the source data.
It also adds a breaking change, when referring to an object within a group, now you get the absolute time, not the local time within that group
> Ensure behaviour is consistent with source data in any order

- src/__tests__/index.spec.ts
Adds a test for the relative durations, to ensure that the order of the objects in the timeline data array has no effect on the resolved durations
Whether the test passes depends on the order of the groups.
It fails if group1 is after group0, but passes if group1 is before group0.
It should not matter what order they are in, and should resolve the same both ways.
> feat: Add test to check order of objects in the source data has no affect on relative duration resolving

- src/__tests__/index.spec.ts
- src/resolver/resolver.ts
Adds a test to verify the order of groups does not affect the resolving of child items
The result varies depending on the order of the groups
> chore: Add test for group order affecting child start time resolving

- src/__tests__/index.spec.ts
- src/resolver/resolver.ts
The problem here is that group2 ends up with an unresolved end due to a claimed circular dependency.
I can get the correct behaviour by giving group2 a duration: `(#group3.start + 600 - #.start) - 2000` which should give the same result.
> chore: Add test for child duration referencing parent end

- src/__tests__/index.spec.ts
- src/resolver/resolver.ts
It is possible to have a child object resolving when the parent group does not, by using a negative start offset.
> chore: Add test for child starting before parent group

- src/__tests__/index.spec.ts
- src/resolver/resolver.ts
TimelineObj.LLayer is now defined as `string | number` so logical triggers should allow it to be a string too.
> fix: Allow string llayer ids in logical triggers

- src/__tests__/index.spec.ts
This adds a failing test due to the order of the logical objects on the timeline producing a different result.
@nytamin I suspect nothing can be done about this due to the way the logical objects are evaluated? Ideally I would expect it to give the object with the later start point priority over the earlier ones
> Order of logical objects

- src/__tests__/index.spec.ts
Looking in particular at the 'Logical triggers 3b' test, the presence of 'head_force_clear' is causing nora_primary_headline to sometimes get a state of undefined. Removing that object gives the expected behaviour from the other objects
The 'Logical triggers 3' is a variant of this, but the 'head_force_clear' causes it to resolve to another logical object instead of the expected absolute object.
Also worth noting, is that the 'head_force_clear' should always be inactive, so should have no effect on the timeline
> Order of logical objects can affect absolute object resolving

- src/__tests__/index.spec.ts
- src/__tests__/lib.spec.ts
- src/lib.ts
- src/resolver/resolver.ts
This case is showing a bad state computation.
layer0 is not getting an object, despite it (o1) enabling on the class which is made active by o5.
Removing the bad0 object, or changing the class it defines produces the correct result. As bad0 is not active in the state, it should not have any effect
> add test for class application in state from inactive object

- src/resolver/__tests__/expression.spec.ts
- src/resolver/expression.ts
- src/resolver/resolver.ts
Fixes expressions where nested single item arrays get produced.
Update the typings of interpretExpression as it can also return a string if the input was a single reference.
Improve the error reporting of validateExpression
> fix: some expressions failing to be converted to objects

- src/__tests__/legacy.spec.ts
- src/lib.ts
- src/resolver/__tests__/resolver.spec.ts
- src/resolver/resolver.ts
- src/resolver/state.ts
A keyframe `enable: { while: '.class0' }` works, but `enable: { while: '!.class0' }` always ends up as unresolved.
This is always the case if the class referenced does not exist on the timeline, but if it does then that the behaviour can vary depending on  if the while on the parent object being either `1` or `'1'`.
> chore: test for keyframe enabler with a negate

- src/lib.ts
- src/resolver/__tests__/expression.spec.ts
- src/resolver/__tests__/resolver.spec.ts
- src/resolver/expression.ts
- src/resolver/resolver.ts
Credit goes to @jesperstarkar who found this bug.
It turns out that a child in a group that is
`enable: '1+1'`
is not equal to
`enable: '2'`
> Child referring parent

- src/resolver/__tests__/resolver.spec.ts
- src/resolver/state.ts
Object `class1` defines a second occurance of a class used by a keyframe enabler.
The keyframe `object0_kf0` does not activate during this, but the normal `object1` work as expected.
> keyframe class enabler not working on second instance of class

- src/resolver/__tests__/resolver.spec.ts
- src/resolver/resolver.ts
* **What is the current behavior?**
When you have two objects that run back-to-back with 2 classes and you have an object or keyframe that is triggered by a combination of a class and a negated class, the _second_ object does not make the object/keyframe resolve correctly.
* **What is the expected behavior?**
Should resolve correctly and consistently.
* **Extra info**
This does work as expected when the objects are not back-to-back
> Continuous combined negated and normal classes on different objects

- src/api/api.ts
- src/resolver/__tests__/resolver.spec.ts
- src/resolver/resolver.ts
Circular dependency exception is thrown, causing the timeline resolve to fail
* **What is the expected behavior?**
As they are very loose selectors, it would be preferable if they could simply ignore the object initiating it.
This behaviour would be useful to be able to insert an object after each other object on a layer. Such as to insert a static titlecard or endcard for a video
> Circular dependency if enabler references own layer or class

- src/__tests__/index.spec.ts
- src/__tests__/legacy.spec.ts
- src/api/api.ts
- src/resolver/__tests__/validate.spec.ts
- src/resolver/resolver.ts
- src/resolver/validate.ts
This PR adds the ability to set instances of a timeline-object.
Like so:
```
const myTimeline = [
{
id: 'video0',
layer: 'L1',
enable: {
instances: [
{start: 0, end: 10},
{start: 25, end: 30},
{start: 97, end: 101},
]
},
content: {}
},
]
```
The intention is that this could be used by a pre-processor of the timeline, which inserts certain elements, that are then used by the timeline resolver.
> feat: be able to provide enable.instances directly in the timeline.

- src/resolver/__tests__/resolver/groups.spec.ts
- src/resolver/resolver.ts
This adds a pair of unit tests, the only difference is that the start of obj1 changes from `0` to `#obj0.start + 0` (which will resolve to 0).
This causes the resolver to produce an incorrect result, with the instance changing from
```
{
"id": "obj1",
"start": 1599753027264.5,
"end": 1599839427264.5,,
"references": []
}
```
to 
```
{
"id": "obj1",
"start": 1599753027264.5,
"end": 86400000,
"references": []
}
```
> chore: unit test for child object end time not being made absolute

- src/resolver/__tests__/resolver/groups.spec.ts
- src/resolver/__tests__/resolver/keyframes.spec.ts
- src/resolver/state.ts
unit test
As shown, there are two groups on the same layer. They are on a named layer, so only one can be active at a time.
The all-states object correctly tracks the times of everything.
But getting a state during the point where the groups 'overlap', can return objects from both groups.
As shown in this test block
```
{
// before 'end' of grp0
const state = Resolver.getState(resolved, 5200)
expect(state.layers['layer1']).toBeTruthy()
expect(state.layers['layer1']).toMatchObject({
id: 'grp1',
})
expect(state.layers['layer0']).toBeFalsy()
}
```
`state.layers['layer0']` ends up with object `grp0_0`, which is incorrect
* **What …
> bug: when groups overlap, child objects can outlive the parent

- src/__tests__/timelineGenerator.ts
- src/index.ts
- src/resolver/__tests__/validate.spec.ts
- src/resolver/expression.ts
- src/resolver/validate.ts
Fix
It is possible to send in strings in id, classes or layers that crashes the Timeline when resolving it.
For example `id: "test--1"`
ids, classes and layers are now validated before resolving.
Also exports a new function, `validateIdString()` that can be used to validate strings to find issues early
> Validate strings

- src/resolver/__tests__/resolver/groups.spec.ts
- src/resolver/state.ts
bug
Sometimes objects can be given a start and end time of the same point in time, and appear in the state as a start with no end
related to https://github.com/SuperFlyTV/supertimeline/pull/79 ?
> fix: instances capped to zero duration get stuck in state

- .github/workflows/audit.yml
- .github/workflows/node.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/sonar.yml
- jest.config.js
- package.json
- src/__tests__/index.spec.ts
- src/__tests__/legacy.spec.ts
- src/resolver/__tests__/expression.spec.ts
- src/resolver/__tests__/resolver/lookupExpression.spec.ts
- src/resolver/__tests__/testlib.ts
- src/resolver/__tests__/validate.spec.ts
- yarn.lock
CI and dependencies update
* CI depended on some Node 12-based actions,
* package.json states that  `"engines": {"node": ">=12"}` is supported
* 
* CI user newer actions
* Dropped Node 12 support (removed Node12 from CI tests)
> update Node versions (drop Node 12)

- src/__tests__/index.spec.ts
- src/__tests__/invalidate.spec.ts
- src/__tests__/performance.spec.ts
- src/__tests__/performance.ts
- src/resolver/CacheHandler.ts
- src/resolver/ResolvedTimelineHandler.ts
- src/resolver/lib/timeline.ts
This is a bug fix
(See unit test)
If Partial Resolving (using cache) is enabled:
On Layer `L0`, we have object `A` and `B`.
If object `A` has changed between resolves, this should affect `B`, since they are on the same layer and collide with eachother.
Currently, this is not taken into account during a resolve.
If Partial Resolving (using cache) is enabled:
If an object is changed between resolves, any object on the same layer (ie can be affected by the change) will be re-resolved.
> Bug fix: A changed object might not affect object on same layer

- src/__tests__/basic.spec.ts
- src/__tests__/index.spec.ts
- src/api/resolvedTimeline.ts
- src/api/resolver.ts
- src/index.ts
- src/resolver/CacheHandler.ts
- src/resolver/LayerStateHandler.ts
- src/resolver/ResolvedTimelineHandler.ts
- src/resolver/ResolverHandler.ts
- src/resolver/StateHandler.ts
- src/resolver/lib/Error.ts
This is a Code improvement.
* **What is the new behavior?**
This PR replaces the debug-tracing to console.log, with logging to `resolvedTimeline.statistics.resolveTrace`.
It also changes a thrown `Error` into a `ResolveError` that contains the (partially resolved) `resolvedTimeline`.
This allows for a consumer of the Timeline resolver to try/catch and better log the `resolveTrace`, to figure out what might have gone wrong.
(This is an attempt to fix a `"Internal Error: There is already an object on layer"` issue in production, see [TSR PR](https://github.com/nrkno/sofie-timeline-state-resolver/pull/351).)
> Add tracing of resolve, for troubleshooting

- README.md
- src/__tests__/groups.spec.ts
- src/api/types.ts
- src/resolver/ReferenceHandler.ts
- src/resolver/ResolvedTimelineHandler.ts
- src/resolver/lib/reference.ts
feature
This adds a shorthand notation for making references to the parent group that an object belongs to.  
This is intended to allow for timing objects to the end of the parent group, without needing to know the id of that group.
I am not 100% sure of the syntax proposed here, maybe there is a better character to use? Equally, I think this makes some sense as its pretending to be a id reference to `@`, which conceptually matches what it is doing.
I am not at all confident in this implementation, I probably have missed some cases in caching or something. Some pointers on more things/cases to test would be …
> feat: add shorthand reference to parent group

- src/resolver/TimelineValidator.ts
- src/resolver/__tests__/TimelineValidator.spec.ts
Minor bug fix in thrown error message
The TimelineValidator throws error with message `"enable.while" and "enable.end" cannot be combined`
The TimelineValidator throws error with message `Object "xyz": "enable.while" and "enable.end" cannot be combined`
> fix: Add missing object id reference to the thrown Validator errors

- src/__tests__/basic.spec.ts
- src/resolver/LayerStateHandler.ts
- src/resolver/ResolvedTimelineHandler.ts
Bug fix
(see unit test)
If an object (A) collides with object (B) that depends on object (C) that is affected by a collision with object (D);
Object A might get the wrong resolved result in certain cases.
This bug only happens in a certain order of objects in the timeline as well as if the names of the layers are in a certain alphabetical order.
When a collision results in re-resolving, all other objects on that layer are also re-resolved.
This fixes the bug, but also decreases performance:
`yarn unit performance` results:
* Before: 3.6 ms
* After: 5.2 ms
> Bug: Object that collide with object that depend on colliding object
